/**
 * Cien trabajos de ejemplo.
 *
 * Son el contenido con el que se muestra la app y con el que se siembra un
 * servidor de prueba. Viven acá y no escritos dos veces, por lo mismo que el
 * catálogo: dos listas iguales en dos archivos se separan solas, y después la
 * app ofrece cosas que el servidor no tiene.
 *
 * Cada fila es [oficio, título, descripción, cantidad, dificultad]. El precio
 * no se escribe: lo calcula el cotizador, así ninguno queda por debajo del
 * piso de su oficio.
 */
export const TRABAJOS = [
  ["jardineria-corte-pasto", "Cortar el pasto y emparejar el borde", "Patio de unos 60 m² con pasto alto. Hay llave de agua y enchufe. Las bolsas las pongo yo.", 3, "BASICA"],
  ["jardineria-corte-pasto", "Podar tres árboles del antejardín", "Son ciruelos, no muy altos. Necesito que se lleven las ramas o las dejen embolsadas.", 4, "MEDIA"],
  ["jardineria-corte-pasto", "Mantención mensual del jardín", "Casa en esquina, pasto adelante y atrás. Busco a alguien fijo para todos los meses.", 4, "BASICA"],
  ["jardineria-corte-pasto", "Cortar pasto antes del arriendo", "Se arrienda la casa el lunes y el patio está impresentable. Urgente.", 3, "MEDIA"],
  ["limpieza-hogar", "Limpieza semanal de departamento", "Dos dormitorios, un baño, cocina americana. Busco alguien para todos los jueves.", 4, "BASICA"],
  ["limpieza-hogar", "Limpieza después de una fiesta", "Cumpleaños de anoche. Living, cocina y terraza. Hay harto vaso y confeti.", 4, "MEDIA"],
  ["limpieza-hogar", "Ordenar y limpiar antes de que lleguen visitas", "Llegan mis suegros el viernes. Casa de un piso, tres dormitorios.", 5, "BASICA"],
  ["limpieza-hogar", "Limpieza de oficina chica", "Dos escritorios, sala de reuniones y un baño. Después de las 19:00.", 3, "BASICA"],
  ["limpieza-profunda", "Limpieza profunda de cocina", "Campana, horno y azulejos con grasa vieja. Necesito que quede como nueva.", 5, "ALTA"],
  ["limpieza-profunda", "Limpieza fin de obra", "Terminamos de remodelar el baño y hay polvo de cemento en toda la casa.", 6, "ALTA"],
  ["limpieza-profunda", "Departamento vacío antes de entregar", "Me voy y tengo que entregarlo impecable para que me devuelvan la garantía.", 5, "MEDIA"],
  ["limpieza-profunda", "Sacar hongos del baño", "Baño sin ventana, hay hongo en las juntas y en el techo. Llevo productos.", 4, "ALTA"],
  ["armado-muebles", "Armar un clóset de dos cuerpos", "Viene en caja de una tienda grande. Tiene puertas corredizas y espejo.", 3, "MEDIA"],
  ["armado-muebles", "Armar una cuna y un cambiador", "Todo sin abrir. Preferiría alguien con paciencia, las instrucciones son un desastre.", 2, "BASICA"],
  ["armado-muebles", "Colgar repisas y un televisor", "Tres repisas flotantes y un televisor de 55 pulgadas. Muro de hormigón.", 3, "MEDIA"],
  ["armado-muebles", "Armar un escritorio en L y una silla", "Llegó hoy. Necesito que quede listo para trabajar mañana temprano.", 2, "BASICA"],
  ["mensajeria", "Llevar unos papeles al centro", "Sobre cerrado a una notaría en Santiago Centro. Hay que esperar el timbre.", 1, "BASICA"],
  ["mensajeria", "Hacer un trámite en el Registro Civil", "Sacar un certificado. Llevo el poder firmado y la plata del trámite.", 1, "MEDIA"],
  ["mensajeria", "Retirar un paquete y traerlo", "Está en una sucursal de correos en Providencia. Cabe en una mochila.", 1, "BASICA"],
  ["paseo-mascotas", "Pasear a Rocco de lunes a viernes", "Labrador de cuatro años, tranquilo pero fuerte. Una hora a las 18:00.", 2, "BASICA"],
  ["paseo-mascotas", "Cuidar dos gatos el fin de semana", "Nos vamos tres días. Hay que darles comida y limpiar la arena.", 3, "BASICA"],
  ["paseo-mascotas", "Llevar a la perra al veterinario", "Tiene hora a las 11:00 en Ñuñoa. Es chica y se deja alzar.", 2, "BASICA"],
  ["cuidado-ninos", "Cuidar a dos niños el sábado a la noche", "Tienen 4 y 7. Ya cenados. Vuelvo cerca de la una.", 5, "MEDIA"],
  ["cuidado-ninos", "Retirar del colegio y acompañar hasta las 19", "Colegio en Providencia, casa a diez cuadras. Hay que darle once y ayudar con tareas.", 4, "MEDIA"],
  ["cuidado-ninos", "Cuidar a una bebé de ocho meses", "Trabajo desde la casa y necesito tres horas sin interrupciones.", 3, "ALTA"],
  ["cuidado-adultos", "Acompañar a mi mamá al control médico", "Tiene 82 años, camina con bastón. Consulta en Las Condes, ida y vuelta.", 4, "MEDIA"],
  ["cuidado-adultos", "Compañía tres tardes por semana", "Mi papá vive solo. Es conversar, ayudarlo con el almuerzo y que no esté solo.", 4, "BASICA"],
  ["cuidado-adultos", "Turno de noche por una semana", "Mi abuela salió de una operación. Alguien con experiencia en cuidados.", 8, "ALTA"],
  ["mozo-evento", "Mozo para un matrimonio chico", "Cincuenta invitados en una casa con patio. Servir y levantar.", 6, "MEDIA"],
  ["mozo-evento", "Dos garzones para un cumpleaños", "Treinta personas, hay barra. De 20:00 a 2:00.", 6, "MEDIA"],
  ["mozo-evento", "Atender una cena de empresa", "Doce personas sentadas, servicio a la mesa. Se pide presentación formal.", 5, "ALTA"],
  ["pintura", "Pintar el living y el pasillo", "Paredes blancas con manchas. Compro la pintura yo, necesito mano de obra.", 45, "MEDIA"],
  ["pintura", "Pintar la reja y el portón", "Fierro con óxido en algunas partes. Hay que lijar antes.", 30, "ALTA"],
  ["pintura", "Pintar dos dormitorios", "Uno queda gris y el otro blanco. Muebles los corro yo.", 40, "BASICA"],
  ["pintura", "Pintar la fachada de la casa", "Casa de un piso, fachada al frente. Hay andamio en la casa.", 60, "ALTA"],
  ["plomeria", "Arreglar una filtración bajo el lavaplatos", "Gotea desde hace dos semanas y ya se hinchó el mueble.", 2, "MEDIA"],
  ["plomeria", "Cambiar el calefont", "El actual no calienta. Ya compré el nuevo, falta instalarlo y certificar.", 3, "ALTA"],
  ["plomeria", "Destapar el desagüe de la ducha", "El agua se queda y baja lentísimo. Segundo piso.", 1, "MEDIA"],
  ["plomeria", "Instalar un lavaplatos nuevo", "Llegó el mueble con el lavaplatos. Hay que conectar agua y desagüe.", 3, "MEDIA"],
  ["electricidad", "Revisar el tablero, salta la térmica", "Salta cada vez que prendo el horno eléctrico. Departamento en tercer piso.", 2, "ALTA"],
  ["electricidad", "Instalar seis enchufes nuevos", "Estamos haciendo home office y faltan tomas en dos piezas.", 4, "MEDIA"],
  ["electricidad", "Cambiar la iluminación a LED", "Doce focos embutidos en el cielo del living y el comedor.", 3, "BASICA"],
  ["electricidad", "Certificado SEC para la ampliación", "Terminamos una pieza nueva y necesito el TE1 para inscribirla.", 4, "ALTA"],
  ["aire-acondicionado", "Instalar un split en el dormitorio", "Ya está comprado, 12.000 BTU. Pared exterior, segundo piso.", 4, "ALTA"],
  ["aire-acondicionado", "Mantención de dos equipos", "No se limpian hace dos veranos y huelen feo al prenderlos.", 3, "MEDIA"],
  ["aire-acondicionado", "Reparar aire que no enfría", "Prende y ventila pero sale el aire tibio. Creo que perdió gas.", 2, "ALTA"],
  ["carpinteria", "Hacer una repisa a medida", "Un hueco de 1,80 por 60. Madera vista, tres bandejas.", 6, "MEDIA"],
  ["carpinteria", "Arreglar una puerta que no cierra", "Se hinchó con la humedad y raspa contra el marco.", 2, "BASICA"],
  ["carpinteria", "Cambiar tablas del deck", "Ocho tablas podridas en la terraza. El resto está bien.", 5, "MEDIA"],
  ["carpinteria", "Hacer un mueble bajo la escalera", "Aprovechar el hueco con cajones. Tengo las medidas y una foto de referencia.", 8, "ALTA"],
  ["albanileria", "Levantar un muro divisorio", "Dividir una pieza grande en dos. Ladrillo y estuco, sin instalación.", 2, "MEDIA"],
  ["albanileria", "Reparar filtración en el techo", "Entra agua por la unión de la ampliación. Cada vez que llueve.", 1, "ALTA"],
  ["albanileria", "Hacer una radier para la bodega", "Tres por tres metros en el patio. El material lo compro yo.", 2, "MEDIA"],
  ["mudanza-flete", "Mudanza de un departamento de un ambiente", "De Ñuñoa a Maipú. Hay ascensor en los dos lados.", 4, "MEDIA"],
  ["mudanza-flete", "Llevar un sillón a la casa de mi hermana", "Sillón de tres cuerpos, no pasa por el ascensor: hay que bajarlo por la escalera.", 3, "ALTA"],
  ["mudanza-flete", "Retirar muebles viejos", "Un ropero y dos veladores para llevar a un punto limpio o donarlos.", 3, "BASICA"],
  ["mudanza-flete", "Mudanza de casa completa", "Tres dormitorios. Somos dos adultos y tenemos todo encajado.", 8, "ALTA"],
  ["cocinero-evento", "Cocinar para un cumpleaños de 25", "Algo simple y rico. Compro yo los insumos con la lista que me pasen.", 5, "MEDIA"],
  ["cocinero-evento", "Cena para ocho, menú de tres tiempos", "Aniversario en casa. Busco alguien que cocine y deje la cocina ordenada.", 5, "ALTA"],
  ["cocinero-evento", "Asado para veinte personas", "Tengo la parrilla y la carne. Necesito quien la maneje bien.", 6, "MEDIA"],
  ["fotografia", "Fotos para un cumpleaños de un año", "Dos horas en una casa con patio. Quiero las fotos editadas.", 3, "MEDIA"],
  ["fotografia", "Fotos de producto para vender online", "Treinta piezas de cerámica. Fondo blanco, buena luz.", 4, "MEDIA"],
  ["fotografia", "Video corto para redes", "Un minuto mostrando el local. Grabación y edición.", 4, "ALTA"],
  ["clases-particulares", "Matemática para segundo medio", "Le está yendo mal en ecuaciones. Dos veces por semana.", 2, "MEDIA"],
  ["clases-particulares", "Inglés conversacional para adulto", "Entiendo bastante pero me trabo al hablar. Una hora, dos veces por semana.", 2, "MEDIA"],
  ["clases-particulares", "Preparar la PAES de lenguaje", "Doy la prueba este año y necesito ordenarme con la comprensión lectora.", 3, "ALTA"],
  ["soporte-tecnico", "El notebook anda lentísimo", "Tarda cinco minutos en prender. Tiene siete años y nunca lo formateé.", 2, "MEDIA"],
  ["soporte-tecnico", "Configurar el wifi en toda la casa", "Casa de dos pisos, arriba no llega la señal. Ya compré un repetidor.", 2, "MEDIA"],
  ["soporte-tecnico", "Recuperar fotos de un disco externo", "Se cayó al suelo y ya no lo reconoce el computador. Hay fotos de años.", 3, "ALTA"],
  ["soporte-tecnico", "Instalar dos computadores nuevos", "Para la oficina. Pasar los archivos de los viejos y dejar todo andando.", 4, "MEDIA"],
  ["traduccion", "Traducir un certificado de estudios", "Del español al inglés, dos páginas. Lo pide una universidad.", 1, "MEDIA"],
  ["traduccion", "Corregir la redacción de mi tesis", "Cuarenta páginas. Ortografía, redacción y coherencia.", 1, "ALTA"],
  ["traduccion", "Traducir la carta de presentación y el CV", "Postulo a un trabajo afuera. Que suene natural, no traducido.", 1, "MEDIA"],
  ["desarrollo-software", "Arreglar el carro de compras de mi tienda", "Tienda en línea de artesanías. A veces se pierde el pedido al pagar.", 6, "ALTA"],
  ["desarrollo-software", "Hacer una página para mi taller mecánico", "Una página simple con servicios, fotos y un botón de WhatsApp.", 8, "MEDIA"],
  ["desarrollo-software", "Automatizar un informe que hago a mano", "Todos los lunes junto datos de tres planillas. Quiero dejar de hacerlo a mano.", 6, "ALTA"],
  ["diseno-grafico", "Logo y tarjetas para una peluquería", "Recién abrimos. Quiero algo simple y que se vea bien en el letrero.", 1, "MEDIA"],
  ["diseno-grafico", "Diseñar la carta del restaurante", "Veinte platos, con fotos. Para imprimir y para el código QR.", 1, "MEDIA"],
  ["diseno-grafico", "Etiquetas para mermeladas caseras", "Cuatro sabores. Vendo en ferias y quiero que se vean más profesionales.", 1, "BASICA"],
  ["contabilidad", "Declaración de renta de una pyme", "Somos tres socios, facturamos hace dos años. Necesito ordenar todo.", 6, "ALTA"],
  ["contabilidad", "Poner al día los libros de contabilidad", "Atrasado ocho meses. Tengo todas las facturas guardadas.", 8, "ALTA"],
  ["contabilidad", "Ayuda para iniciar actividades", "Quiero emitir boletas y no sé por dónde empezar.", 2, "MEDIA"],
  ["abogado-dia", "Abogado para una audiencia laboral", "Audiencia de conciliación, media jornada en tribunales. Envío el expediente.", 1, "ALTA"],
  ["abogado-dia", "Representación en una mediación familiar", "Tema de pensión de alimentos. Una jornada en el centro de mediación.", 1, "ALTA"],
  ["abogado-consulta", "Consulta por un despido", "Me despidieron por necesidades de la empresa y creo que no corresponde.", 1, "MEDIA"],
  ["abogado-consulta", "Revisar un contrato de arriendo", "Me pasaron el contrato y tiene cláusulas que no entiendo.", 1, "MEDIA"],
  ["abogado-consulta", "Consulta por una herencia", "Falleció mi papá y somos cuatro hermanos. Quiero saber cómo se hace.", 2, "ALTA"],
  ["ingenieria-civil", "Cálculo estructural para ampliar el segundo piso", "Quiero levantar una pieza sobre el garaje. Necesito planos firmados.", 1, "ALTA"],
  ["ingenieria-civil", "Informe estructural por grietas", "Aparecieron grietas después del último temblor. Necesito saber si es grave.", 1, "ALTA"],
  ["ingenieria-electrica", "Proyecto eléctrico para una ampliación", "Sesenta metros cuadrados nuevos. Necesito el proyecto para la SEC.", 4, "ALTA"],
  ["ingenieria-electrica", "Revisar el empalme del local", "Queremos poner dos hornos y no sé si la potencia alcanza.", 3, "MEDIA"],
  ["arquitectura", "Anteproyecto para regularizar una ampliación", "La pieza está hace años y quiero regularizarla en la municipalidad.", 6, "ALTA"],
  ["arquitectura", "Planos para remodelar la cocina", "Quiero tirar un muro y abrirla al living. Necesito planos y permiso.", 5, "ALTA"],
  ["topografia", "Levantamiento topográfico del terreno", "Terreno de media hectárea fuera de Santiago. Para subdividir.", 1, "ALTA"],
  ["peritaje", "Tasación de un departamento", "Para una compraventa. Departamento de 68 m² en Ñuñoa.", 1, "MEDIA"],
  ["peritaje", "Peritaje por humedad en el departamento", "Discusión con la administración del edificio. Necesito un informe firmado.", 1, "ALTA"],
  ["enfermeria", "Curaciones después de una operación", "Mi mamá salió de una cirugía de rodilla. Curación día por medio.", 2, "ALTA"],
  ["enfermeria", "Poner una inyección tres días seguidos", "Tratamiento indicado por el médico. Tengo la receta y las ampollas.", 2, "MEDIA"],
  ["kinesiologia", "Sesiones para recuperar el hombro", "Tendinitis. El traumatólogo indicó diez sesiones a domicilio.", 1, "MEDIA"],
  ["kinesiologia", "Kinesiología respiratoria para mi hijo", "Tiene tres años y quedó con mucha secreción después de un resfrío.", 1, "ALTA"],
];
